import numpy as np
import pickle

def is_antisymmetric(tensor):
    # Get the shape of the tensor
    shape = tensor.shape

    # Check if the tensor is rectangular
    if len(shape) != 8:
        raise ValueError('Tensor must have 8 indices')
    for i in range(4):
        if shape[i] != shape[i+4]:
            raise ValueError('Tensor must be rectangular')

    # Check if the tensor is antisymmetric
    for i in range(shape[0]):
        for j in range(i+1, shape[1]):
            for k in range(shape[2]):
                for l in range(k+1, shape[3]):
                    for m in range(shape[4]):
                        for n in range(m+1, shape[5]):
                            for p in range(shape[6]):
                                for q in range(p+1, shape[7]):
                                    if not np.allclose(tensor[i,j,k,l,m,n,p,q],tensor[j,i,k,l,n,m,p,q]):#tensor[i,j,k,l,m,n,p,q] != -tensor[j,i,k,l,n,m,p,q]:
                                        return False,[i,j,k,l,m,n,p,q],tensor[i,j,k,l,m,n,p,q],tensor[j,i,k,l,n,m,p,q]

    return True


def unsym_residQf1(ccd_kernel,g,t2_aa,o,v,nocc,nvir,g2=None):

    Roooovvvv = np.zeros((nocc,nocc,nocc,nocc,nvir,nvir,nvir,nvir))
    t=t2_aa.transpose(2,3,0,1)
    v_oo=g[o,o,o,o]
    v_vo=g[o,v,o,v]
    v_vv=g[v,v,v,v]
    v_m2=g[v,v,o,o]
    # Do base-line (Qf) style of constructing T4
    Roooovvvv += -0.062500000 * np.einsum("imab,jncd,klmn->ijklabcd",t,t,v_oo,optimize="optimal")
    Roooovvvv += -0.250000000 * np.einsum("imab,jkce,lemd->ijklabcd",t,t,v_vo,optimize="optimal")
    Roooovvvv += -0.062500000 * np.einsum("ijae,klbf,efcd->ijklabcd",t,t,v_vv,optimize="optimal")

    Roooovvvv_t2_dump=antisym_t4_residual(Roooovvvv,nocc,nvir)# dump third-order T4
    with open('roooovvvv_t4_third.pickle', 'wb') as handle:
        pickle.dump(Roooovvvv_t2_dump, handle) 

    if ccd_kernel.cc_type == "CCD(Qf*)":# tack on the W-2 T2^3 contrib to T4
        Roooovvvv_t23 = -0.031250000 * np.einsum("imab,jncd,klef,efmn->ijklabcd",t,t,t,v_m2,optimize="optimal")
        Roooovvvv_t23 += 0.250000000 * np.einsum("imab,jkce,lndf,efmn->ijklabcd",t,t,t,v_m2,optimize="optimal")
        Roooovvvv_t23 += -0.031250000 * np.einsum("mnab,ijce,kldf,efmn->ijklabcd",t,t,t,v_m2,optimize="optimal")
        Roooovvvv_t23_dump = antisym_t4_residual(Roooovvvv_t23,nocc,nvir)  # dump fourth-order T4
        with open('roooovvvv_t4_fourth.pickle', 'wb') as handle:
            pickle.dump(Roooovvvv_t23_dump, handle)   
        Roooovvvv +=Roooovvvv_t23

    Roooovvvv=antisym_t4_residual(Roooovvvv,nocc,nvir)
    return Roooovvvv


def test_permute_t4ov(t4_ov):
    antisym_t4 = 1 * np.einsum("ijklabcd->ijklabcd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijklabdc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijklacbd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijklacdb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijkladbc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijkladcb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijklcbad", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijklcbda", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijkldbac", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijkldbca", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijkldcba", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijlkabcd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijlkabdc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijlkacbd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijlkacdb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijlkadbc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijlkadcb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijlkcbad", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijlkcbda", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijlkdbac", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijlkdbca", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijlkdcba", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjabcd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjabdc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjacbd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjacdb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjadbc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjadcb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjcbad", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjcbda", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjdbac", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjdbca", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjdcba", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jiklabcd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jiklabdc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jiklacbd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jiklacdb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jikladbc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jikladcb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jiklcbad", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jiklcbda", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jikldbac", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jikldbca", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jikldcba", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jlkiabcd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jlkiabdc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jlkiacbd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jlkiacdb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jlkiadbc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jlkiadcb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jlkicbad", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jlkicbda", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jlkidbac", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->jlkidbca", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->jlkidcba", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjilabcd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjilabdc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjilacbd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjilacdb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjiladbc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjiladcb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjilcbad", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjilcbda", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjildbac", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjildbca", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjildcba", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjliabcd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjliabdc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjliacbd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjliacdb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjliadbc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjliadcb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjlicbad", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjlicbda", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjlidbac", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjlidbca", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjlidcba", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijabcd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijabdc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijacbd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijacdb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijadbc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijadcb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijcbad", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijcbda", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijdbac", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijdbca", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijdcba", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->likjabcd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->likjabdc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->likjacbd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->likjacdb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->likjadbc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->likjadcb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->likjcbad", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->likjcbda", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->likjdbac", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->likjdbca", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->likjdcba", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljikabcd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljikabdc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljikacbd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljikacdb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljikadbc", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljikadcb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljikcbad", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljikcbda", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljikdbac", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljikdbca", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljikdcba", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkiabcd", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkiabdc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkiacbd", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkiacdb", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkiadbc", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkiadcb", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkicbad", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkicbda", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkidbac", t4_ov)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkidbca", t4_ov)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkidcba", t4_ov)
    return antisym_t4


def test_permute_t4vv(t4_vv):
    antisym_t4 = 1 * np.einsum("ijklabcd->ijklabcd", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijklacbd", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijkladcb", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijklcbad", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijklcdab", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijkldbca", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ikjlabcd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjlacbd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjladcb", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjlcbad", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ikjlcdab", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjldbca", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjabcd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjacbd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjadcb", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjcbad", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjcdab", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjdbca", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjilabcd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjilacbd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjiladcb", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjilcbad", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjilcdab", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjildbca", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkiabcd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkiacbd", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkiadcb", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkicbad", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkicdab", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkidbca", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->lkjiabcd", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->lkjiacbd", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->lkjiadcb", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->lkjicbad", t4_vv)
    antisym_t4 += 1 * np.einsum("ijklabcd->lkjicdab", t4_vv)
    antisym_t4 += -1 * np.einsum("ijklabcd->lkjidbca", t4_vv)
    return antisym_t4

def test_permute_t4oo(t4_oo):
    antisym_t4 = 1 * np.einsum("ijklabcd->ijklabcd", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijklacbd", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijkladcb", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijklcbad", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ijkldbca", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ijkldcba", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ikjlabcd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjlacbd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjladcb", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjlcbad", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ikjldbca", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ikjldcba", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjabcd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjacbd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjadcb", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjcbad", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ilkjdbca", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ilkjdcba", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjilabcd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjilacbd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjiladcb", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjilcbad", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->kjildbca", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->kjildcba", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijabcd", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijacbd", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijadcb", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijcbad", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->klijdbca", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->klijdcba", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkiabcd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkiacbd", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkiadcb", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkicbad", t4_oo)
    antisym_t4 += 1 * np.einsum("ijklabcd->ljkidbca", t4_oo)
    antisym_t4 += -1 * np.einsum("ijklabcd->ljkidcba", t4_oo)
    return antisym_t4

def permute_t4ov_resid(g_ov,t,residual=None,do_custom=False):
    if do_custom==True:
        t4_ov=np.einsum("aeij,bcmk,mdle->abcdijkl",t,t,g_ov)
    else:
        t4_ov=residual
        
    antisym_t4 = 1 * np.einsum("abcdijkl->abcdijkl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdijlk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdikjl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abcdiklj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abcdiljk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdilkj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdkjil", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abcdkjli", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abcdklij", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abcdljik", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdljki", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abdcijkl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abdcijlk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abdcikjl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abdciklj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abdciljk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abdcilkj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abdckjil", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abdckjli", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abdcklij", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->abdcljik", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->abdcljki", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbijkl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbijlk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbikjl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbiklj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbiljk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbilkj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbkjil", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbkjli", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbklij", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbljik", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbljki", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdijkl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdijlk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdikjl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdiklj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdiljk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdilkj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdkjil", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdkjli", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdklij", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdljik", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdljki", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->badcijkl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->badcijlk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->badcikjl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->badciklj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->badciljk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->badcilkj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->badckjil", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->badckjli", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->badcklij", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->badcljik", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->badcljki", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bdcaijkl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bdcaijlk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bdcaikjl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bdcaiklj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bdcailjk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bdcailkj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bdcakjil", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bdcakjli", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bdcaklij", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->bdcaljik", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->bdcaljki", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadijkl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadijlk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadikjl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadiklj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadiljk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadilkj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadkjil", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadkjli", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadklij", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadljik", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadljki", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbdaijkl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbdaijlk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbdaikjl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbdaiklj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbdailjk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbdailkj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbdakjil", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbdakjli", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbdaklij", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbdaljik", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbdaljki", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cdabijkl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabijlk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabikjl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cdabiklj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cdabiljk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabilkj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabkjil", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cdabkjli", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cdabklij", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->cdabljik", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabljki", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dacbijkl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dacbijlk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dacbikjl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dacbiklj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dacbiljk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dacbilkj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dacbkjil", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dacbkjli", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dacbklij", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dacbljik", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dacbljki", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbacijkl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbacijlk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbacikjl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbaciklj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbaciljk", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbacilkj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbackjil", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbackjli", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbacklij", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbacljik", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbacljki", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbcaijkl", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcaijlk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcaikjl", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbcaiklj", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbcailjk", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcailkj", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcakjil", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbcakjli", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbcaklij", t4_ov)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbcaljik", t4_ov)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcaljki", t4_ov)
    return antisym_t4

def permute_t4vv_resid(t4_vv):
    antisym_t4 = 1 * np.einsum("abcdijkl->abcdijkl", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdikjl", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdilkj", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdkjil", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->abcdklij", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdljki", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->abdcijkl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->abdcikjl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->abdcilkj", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->abdckjil", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->abdcklij", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->abdcljki", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbijkl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbikjl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbilkj", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbkjil", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbklij", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbljki", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdijkl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdikjl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdilkj", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdkjil", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->bacdklij", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->bacdljki", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->badcijkl", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->badcikjl", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->badcilkj", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->badckjil", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->badcklij", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->badcljki", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadijkl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadikjl", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadilkj", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadkjil", t4_vv)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadklij", t4_vv)
    
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadljki", t4_vv)
    
    return antisym_t4

def permute_t4oo_resid(t4_oo):
    antisym_t4 = 1 * np.einsum("abcdijkl->abcdijkl", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdijlk", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdilkj", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdjikl", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->abcdjilk", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->abcdkjil", t4_oo)

    antisym_t4 += -1 * np.einsum("abcdijkl->acbdijkl", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->acbdijlk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->acbdilkj", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->acbdjikl", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->acbdjilk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->acbdkjil", t4_oo)

    antisym_t4 += -1 * np.einsum("abcdijkl->adcbijkl", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbijlk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbilkj", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbjikl", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->adcbjilk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->adcbkjil", t4_oo)
    
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadijkl", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadijlk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadilkj", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadjikl", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->cbadjilk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->cbadkjil", t4_oo)

    antisym_t4 += 1 * np.einsum("abcdijkl->cdabijkl", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabijlk", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabilkj", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabjikl", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->cdabjilk", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->cdabkjil", t4_oo)


    antisym_t4 += -1 * np.einsum("abcdijkl->dbcaijkl", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcaijlk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcailkj", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcajikl", t4_oo)
    antisym_t4 += -1 * np.einsum("abcdijkl->dbcajilk", t4_oo)
    antisym_t4 += 1 * np.einsum("abcdijkl->dbcakjil", t4_oo)
    return antisym_t4
def antisym_t4_residual(Roooovvvv,nocc,nvirt):
    Roooovvvv_anti = np.zeros((nocc,nocc,nocc,nocc,nvirt,nvirt,nvirt,nvirt))

    Roooovvvv_anti =  1 * np.einsum("ijklabcd->ijklabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijklacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijkladcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijkladbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijklbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijklbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijklbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijklcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijklcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijklcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijklcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijkldbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijkldbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijkldcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijkldcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijkldacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijkldabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkdbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkdbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkdcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkdcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ijlkdacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ijlkdabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjladcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjladbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjlcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjlcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjldbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjldbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjldcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjldcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikjldacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikjldabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljdbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljdbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljdcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljdcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ikljdacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ikljdabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjdbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjdbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjdcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjdcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ilkjdacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ilkjdabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkdbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkdbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkdcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkdcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->iljkdacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->iljkdabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jikladcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jikladbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jiklcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jiklcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jikldbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jikldbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jikldcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jikldcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jikldacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jikldabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkdbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkdbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkdcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkdcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jilkdacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jilkdabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkiladcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkiladbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkilcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkilcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkildbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkildbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkildcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkildcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkildacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkildabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkliabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkliabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkliacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkliacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jkliadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jkliadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklibacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklibadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklibcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklibcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklibdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklibdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklicbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklicbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklicabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklicadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklicdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklicdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklidbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklidbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklidcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklidcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jklidacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jklidabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkiabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkiabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkiacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkiacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkiadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkiadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkibacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkibadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkibcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkibcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkibdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkibdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkicbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkicbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkicabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkicadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkicdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkicdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkidbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkidbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkidcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkidcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlkidacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlkidabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikdbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikdbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikdcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikdcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->jlikdacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->jlikdabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjiladcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjiladbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjilcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjilcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjildbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjildbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjildcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjildcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjildacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjildabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjliabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjliabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjliacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjliacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjliadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjliadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlibacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlibadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlibcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlibcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlibdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlibdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlicbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlicbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlicabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlicadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlicdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlicdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlidbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlidbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlidcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlidcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kjlidacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kjlidabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijladcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijladbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijlcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijlcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijldbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijldbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijldcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijldcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kijldacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kijldabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljdbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljdbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljdcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljdcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kiljdacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kiljdabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijdbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijdbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijdcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijdcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->klijdacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->klijdabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljiabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljiabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljiacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljiacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljiadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljiadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljibacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljibadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljibcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljibcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljibdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljibdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljicbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljicbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljicabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljicadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljicdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljicdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljidbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljidbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljidcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljidcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->kljidacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->kljidabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkiabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkiabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkiacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkiacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkiadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkiadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkibacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkibadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkibcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkibcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkibdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkibdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkicbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkicbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkicabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkicadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkicdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkicdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkidbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkidbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkidcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkidcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljkidacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljkidabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikdbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikdbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikdcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikdcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->ljikdacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->ljikdabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjiabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjiabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjiacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjiacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjiadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjiadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjibacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjibadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjibcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjibcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjibdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjibdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjicbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjicbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjicabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjicadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjicdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjicdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjidbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjidbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjidcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjidcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkjidacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkjidabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijdbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijdbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijdcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijdcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lkijdacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lkijdabc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjabcd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjabdc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjacbd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjacdb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjadcb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjadbc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjbacd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjbadc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjbcad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjbcda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjbdca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjbdac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjcbad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjcbda", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjcabd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjcadb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjcdab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjcdba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjdbca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjdbac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjdcba", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjdcab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->likjdacb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->likjdabc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkabcd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkabdc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkacbd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkacdb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkadcb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkadbc", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkbacd", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkbadc", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkbcad", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkbcda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkbdca", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkbdac", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkcbad", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkcbda", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkcabd", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkcadb", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkcdab", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkcdba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkdbca", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkdbac", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkdcba", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkdcab", Roooovvvv)
    Roooovvvv_anti +=  -1 * np.einsum("ijklabcd->lijkdacb", Roooovvvv)
    Roooovvvv_anti +=  1 * np.einsum("ijklabcd->lijkdabc", Roooovvvv)
    return Roooovvvv_anti
